packages:
  - packages/app
  - packages/config
  - packages/ui
  - packages/native-app
catalog:
  solid-js: ^1.9.5
  '@solidjs/router': ^0.15.1
  tailwindcss: ^4.1.1
  '@tailwindcss/vite': ^4.1.1
nodeLinker: hoisted
